version: '3'
networks:
    inkanet:
      ipam:
        config:
          - subnet: 192.168.0.0/24

services:
  proxy:
    image: traefik:v1.7
    command: --docker.watch --api --docker.exposedbydefault=false --docker --defaultentrypoints="http" --entryPoints="Name:http Address::80"
    ports:
    - "80:80"     #The HTTP port
    - "8080:8080" #The Web UI (enabled by --api)
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:cached #So that Traefik can listen to the Docker events

  product-info-service:
    build:
      context: ./product-info-service/
      dockerfile: Dockerfile
    ports:
    - "4000:4000"
    environment:
    - PORT=4000
    - IMAGE_URL=http://192.168.0.4:4001/
    - PRICE_URL=http://192.168.0.5:4002/
    networks:
      inkanet:
        ipv4_address: 192.168.0.10
    labels:
    - traefik.enable=true
    - traefik.port=4000

  image-service:
    build:
      context: ./image-service/
      dockerfile: Dockerfile
    ports:
    - "4001:4001"
    environment:
    - PORT=4001
    networks:
      inkanet:
        ipv4_address: 192.168.0.4
    labels:
    - traefik.enable=true
    - traefik.port=4001

  price-service:
    build:
      context: ./price-service/
      dockerfile: Dockerfile
    environment:
    - PORT=4002
    ports:
    - "4002:4002"
    networks:
      inkanet:
        ipv4_address: 192.168.0.5
    labels:
    - traefik.enable=true
    - traefik.port=4002